export const cuentas = [
  {
    id: 1,
    contrasena: "1234",
    rut: "00",
    nombre: "Camilo",
    apellidos: "Tapia Sepulveda",
    correo: "camilo@gmail.com",
    rol: "admin",
    fotoPerfil: "https://sm.ign.com/ign_es/news/n/netflixs-l/netflixs-live-action-avatar-the-last-airbender-gets-first-lo_ahdu.jpg",
  },
  {
    id: 2,
    contrasena: "1234",
    rut: "11",
    nombre: "Camilo",
    apellidos: "Tapia Sepulveda",
    correo: "camilo@gmail.com",
    rol: "cliente",
    fotoPerfil: "https://sm.ign.com/ign_es/news/n/netflixs-l/netflixs-live-action-avatar-the-last-airbender-gets-first-lo_ahdu.jpg",
  },
  {
    id: 3,
    contrasena: "1234",
    rut: "22",
    nombre: "Matias",
    apellidos: "Pino Saá",
    correo: "matias@gmail.com",
    rol: "proveedor",
    fotoPerfil: "https://ps.w.org/user-avatar-reloaded/assets/icon-256x256.png?rev=2540745",
  },
  {
    id: 4,
    contrasena: "1234",
    rut: "33",
    nombre: "Roberto",
    apellidos: "Albino",
    correo: "Roberto@gmail.com",
    rol: "proveedor",
    fotoPerfil:
      "https://w1.pngwing.com/pngs/743/500/png-transparent-circle-silhouette-logo-user-user-profile-green-facial-expression-nose-cartoon.png",
  },
  {
    id: 5,
    contrasena: "1234",
    rut: "44",
    nombre: "Alberto",
    apellidos: "raro",
    correo: "Alberto@gmail.com",
    rol: "cliente",
    fotoPerfil:
      "https://w1.pngwing.com/pngs/743/500/png-transparent-circle-silhouette-logo-user-user-profile-green-facial-expression-nose-cartoon.png",
  },
];
