export const productos = [
  {
    id: 1,
    codigoBarra: "1",
    producto: "Leche",
    categoria: "Alimentos y bebidas",
    cantidad: 1,
    fecha: new Date(),
    imagen: "https://mercadolavega.cl/wp-content/uploads/2021/02/Leche-entera-colun-litro-2.jpg",
    precio: 100,
    clienteId: 2,
    proveedorId: 4,
  },
  {
    id: 2,
    codigoBarra: "2",
    producto: "Televisor",
    categoria: "Electrónica",
    fecha: new Date(),
    imagen: "https://www.lg.com/cl/images/televisores/md07578586/gallery/D-2.jpg",
    cantidad: 2,
    precio: 200,
    clienteId: 5,
    proveedorId: 3,
  },
  {
    id: 3,
    codigoBarra: "3",
    fecha: new Date(),
    imagen: "https://imag.bonviveur.com/pan-de-trigo-rustico-foto-principal.jpg",
    producto: "Pan",
    categoria: "Alimentos y bebidas",
    cantidad: 3,
    precio: 300,
    clienteId: 2,
    proveedorId: 4,
  },
  {
    id: 4,
    codigoBarra: "4",
    fecha: new Date(),
    imagen: "https://www.lg.com/cl/images/lavadoras/md07521005/gallery/D-1.jpg",
    producto: "Lavadora",
    categoria: "Electrodomésticos",
    cantidad: 4,
    precio: 400,
    clienteId: 5,
    proveedorId: 3,
  },
  {
    id: 5,
    codigoBarra: "7800026789858",
    producto: "Aradix 20 mg 30 comprimidos",
    fecha: new Date(),
    imagen: "https://andreuprados.com/wp-content/uploads/2017/01/apple_0.jpg.webp",
    categoria: "medicina",

    cantidad: 5,
    precio: 500,
    clienteId: 2,
    proveedorId: 4,
  },
  {
    id: 6,
    codigoBarra: "6",
    fecha: new Date(),
    imagen: "https://www.lg.com/cl/images/refrigeradores/md07551794/gallery/DZ-01.jpg",
    producto: "Refrigerador",
    categoria: "Electrodomésticos",
    cantidad: 6,
    precio: 600,
    clienteId: 5,
    proveedorId: 3,
  },
  {
    id: 7,
    codigoBarra: "7",
    fecha: new Date(),
    imagen: "https://comercialdavila.cl/wp-content/uploads/2020/07/arroz-agroprodex-1kg.jpg",
    producto: "Arroz",
    categoria: "Alimentos y bebidas",
    cantidad: 7,
    precio: 700,
    clienteId: 2,
    proveedorId: 4,
  },
  {
    id: 8,
    codigoBarra: "8",
    fecha: new Date(),
    imagen: "https://www.lg.com/cl/images/microondas/md06033256/gallery/M001.jpg",
    producto: "Horno de microondas",
    categoria: "Electrodomésticos",
    cantidad: 8,
    precio: 800,
    clienteId: 5,
    proveedorId: 3,
  },
  {
    id: 9,
    codigoBarra: "9",
    fecha: new Date(),
    imagen: "https://andreuprados.com/wp-content/uploads/2017/01/apple_0.jpg.webp",
    producto: "Cereal",
    categoria: "Alimentos y bebidas",
    cantidad: 9,
    precio: 900,
    clienteId: 2,
    proveedorId: 4,
  },
  {
    id: 10,
    codigoBarra: "10",
    fecha: new Date(),
    imagen: "https://www.hbt.cl/media/catalog/product/cache/2334da356b40c2e91982d081e902ff54/3/2/32713FotoAmbientada6_2.jpg",
    producto: "Lavavajillas",
    categoria: "Electrodomésticos",
    cantidad: 10,
    precio: 1000,
    clienteId: 5,
    proveedorId: 3,
  },
];
