export const productos = [
  {
    id: 0,
    codigoBarra: "0",
    producto: "Leche",
    categoria: "Alimentos y bebidas",
    cantidad: 1,
    precio: 100,
    clienteId: 2,
    proveedorId: 4,
  },
  {
    id: 1,
    codigoBarra: "1",
    producto: "Televisor",
    categoria: "Electrónica",
    cantidad: 2,
    precio: 200,
    clienteId: 5,
    proveedorId: 3,
  },
  {
    id: 2,
    codigoBarra: "2",
    producto: "Pan",
    categoria: "Alimentos y bebidas",
    cantidad: 3,
    precio: 300,
    clienteId: 2,
    proveedorId: 4,
  },
  {
    id: 3,
    codigoBarra: "3",
    producto: "Lavadora",
    categoria: "Electrodomésticos",
    cantidad: 4,
    precio: 400,
    clienteId: 5,
    proveedorId: 3,
  },
  {
    id: 4,
    codigoBarra: "4",
    producto: "Manzanas",
    categoria: "Alimentos y bebidas",
    cantidad: 5,
    precio: 500,
    clienteId: 2,
    proveedorId: 4,
  },
  {
    id: 5,
    codigoBarra: "5",
    producto: "Refrigerador",
    categoria: "Electrodomésticos",
    cantidad: 6,
    precio: 600,
    clienteId: 5,
    proveedorId: 3,
  },
  {
    id: 6,
    codigoBarra: "6",
    producto: "Arroz",
    categoria: "Alimentos y bebidas",
    cantidad: 7,
    precio: 700,
    clienteId: 2,
    proveedorId: 4,
  },
  {
    id: 7,
    codigoBarra: "7",
    producto: "Horno de microondas",
    categoria: "Electrodomésticos",
    cantidad: 8,
    precio: 800,
    clienteId: 5,
    proveedorId: 3,
  },
  {
    id: 8,
    codigoBarra: "8",
    producto: "Cereal",
    categoria: "Alimentos y bebidas",
    cantidad: 9,
    precio: 900,
    clienteId: 2,
    proveedorId: 4,
  },
  {
    id: 9,
    codigoBarra: "9",
    producto: "Lavavajillas",
    categoria: "Electrodomésticos",
    cantidad: 10,
    precio: 1000,
    clienteId: 5,
    proveedorId: 3,
  },
];
